# Generated by Django 5.0.4 on 2024-04-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='MYR', max_length=30),
            preserve_default=False,
        ),
    ]
