# Generated by Django 5.0.4 on 2024-10-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_subject',
            field=models.CharField(max_length=200, null=True, verbose_name='Notification subject'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='custom_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='astoneapp.customuser'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='astoneapp.seller'),
        ),
    ]
