# Generated by Django 5.0.4 on 2024-10-02 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unpaid', models.PositiveBigIntegerField(default=0)),
                ('to_processed_shipment', models.PositiveBigIntegerField(default=0)),
                ('processed_shipment', models.PositiveBigIntegerField(default=0)),
                ('pending_cancellation', models.PositiveBigIntegerField(default=0)),
                ('pending_return', models.PositiveBigIntegerField(default=0)),
                ('removed_product', models.PositiveBigIntegerField(default=0)),
                ('sold_product', models.PositiveBigIntegerField(default=0)),
                ('pending_promotion', models.PositiveBigIntegerField(default=0)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='astoneapp.seller')),
            ],
        ),
    ]
