# Generated by Django 5.0.4 on 2024-08-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='shop_name',
            field=models.TextField(default='', help_text='shop name'),
        ),
    ]
