# Generated by Django 5.0.4 on 2024-10-01 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='astoneapp.product'),
        ),
    ]
