# Generated by Django 5.0.4 on 2024-10-15 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0002_notification_notif_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='astoneapp.seller'),
        ),
    ]
