# Generated by Django 5.0.4 on 2024-08-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0002_seller_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion_price',
            field=models.DecimalField(decimal_places=2, default=-1.0, help_text='price of the product', max_digits=10),
        ),
    ]
