# Generated by Django 5.0.4 on 2024-04-29 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0002_product_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The public id of the uploaded file', max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('name', models.CharField(help_text='The original name of the uploaded image', max_length=100)),
                ('width', models.IntegerField(help_text='Width in pixels')),
                ('height', models.IntegerField(help_text='Height in pixels')),
                ('format', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', help_text='category of the product', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(default=list, help_text='array of available colors for the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', help_text='description of the product', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(default=list, help_text='array of available sizes for the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveBigIntegerField(default=0, help_text='available stock of the product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='MYR', help_text="currency of the product's price", max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', help_text='name of the product', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='price of the product', max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='astoneapp.image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='astoneapp.product')),
            ],
            bases=('astoneapp.image',),
        ),
    ]
