# Generated by Django 5.0.4 on 2024-04-29 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0002_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', help_text='category of the product', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(default=list, help_text='array of available colors for the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', help_text='description of the product', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(default=list, help_text='array of available sizes for the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveBigIntegerField(default=0, help_text='available stock of the product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='MYR', help_text="currency of the product's price", max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', help_text='name of the product', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='price of the product', max_digits=10),
        )
    ]
