# Generated by Django 5.0.4 on 2024-08-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0003_product_promotion_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='original price of the product', max_digits=10),
        ),
    ]
