# Generated by Django 5.0.4 on 2024-05-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0004_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveBigIntegerField(default=0, help_text='available rating of the product'),
        ),
    ]
