# Generated by Django 5.0.4 on 2024-08-26 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0004_product_original_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage for the promotion', max_digits=5)),
                ('start_date', models.DateTimeField(help_text='Promotion start date')),
                ('end_date', models.DateTimeField(help_text='Promotion end date')),
                ('is_active', models.BooleanField(default=True, help_text='Is the promotion currently active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='astoneapp.product')),
            ],
        ),
    ]
