# Generated by Django 5.0.4 on 2024-08-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0005_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='shop_name',
            field=models.TextField(default='shop', help_text='shop name'),
        ),
    ]
