# Generated by Django 5.0.4 on 2024-05-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0005_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=list, help_text='array of available category for the product'),
        ),
    ]
