# Generated by Django 5.0.4 on 2024-05-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0005_producttoimage'),
        ('astoneapp', '0006_alter_product_category'),
    ]

    operations = [
    ]
