# Generated by Django 5.0.4 on 2024-08-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0008_cart_order_product_brand_product_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(default='#FF0000', help_text='Hex code for the color of the product', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='M', help_text='Size of the product', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='#FF0000', help_text='Hex code for the color of the product', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='M', help_text='Size of the product', max_length=10),
        ),
    ]
