# Generated by Django 5.0.4 on 2024-08-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0009_cartitem_color_cartitem_size_orderitem_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
