# Generated by Django 5.0.4 on 2024-08-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astoneapp', '0014_customuser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
    ]
