version: "3.8"

services:
  web: 
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_db
    
  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data    
    environment:
      - POSTGRES=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}

  db:
    image: postgres:latest
    ports:
      - '4020:5432'
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes: 
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

volumes:
  postgres_data:
